apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: konflux-test-container
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: konflux-test-container
    app.kubernetes.io/part-of: konflux-test-container
  name: konflux-test-container
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: konflux-test-container
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: konflux-test-container
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/tmlcoch-tenant/konflux-test-container/konflux-test-container@sha256:aadb76e283307d50dcbedc6c72b53a62e25908d04ba1c09b2c82495c9cfdbe18
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
